### ISSUE TITLE
Rob's questions

### ISSUE THREAD

**Issue by ccharp** [stevezhee/eel#4]
1) Label and branch weirdness
  So was trying to build an infinite loop, something like this

```
loop$:
b loop$
```

  I had generated some LLVM IR that looked like this

```
LO:
br %LO
```

  But it gave me an assembler error: expected instruction opcode.

  So I tried a few things, but in the end the only thing that worked for me was generating the branch first, then the label:

```
br %L0
L0:
br %L0
```

  What's going on? Is there some weird LLVM IR thing I couldn't find? Granted I also couldn't find any examples with a branch before the label. But that doesn't mean anything.

2) Int to ptr
  I needed to write a value to a specific, known memory address:

```
mov r0, 0x20200000
str r1,[r0, #4]
```

  store in Eel is: V a -> V (Ptr a) -> something
  And I was struggling with getting some valid LLVM IR generated that would look like the following:

```
%ptr = inttoptr i32 0x20200000 to i32 *
store i32 %val, i32 * %ptr
```

  But then again I don't know how to do this without the inttoptr function. Tips?

**Comment by stevezhee** [comment]
#1 - there is an implicit ordering on the generated llvm code basic blocks:
label:
<instructions>
control instruction

This isn't enforced by the type system but it could be if we found it necessary.

#2 I think making pointers an instance of the Lit class will solve this without the need for inttoptr.  Rob said he'll take a shot at implementing this.

**Comment by robfblair** [comment]
I'm going to close this since my questions have been answered!
